version: '3'
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_DB: development
      POSTGRES_PASSWORD: development
      POSTGRES_USER: development
    ports: 
     - 5432:5432
    volumes:
     - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql