version: '3'
services: 
  backend:
    build: .
    env_file: .env
    ports: 
      - 4000:4000
    networks: 
      - local
    volumes: 
      - .:/usr/app/server

  postgres:
    image: postgres
    ports: 
      - 5432:5432
    volumes:
     - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file: .env
    networks: 
      - local

networks: 
  local:
    driver: bridge